version: '3.4'

services:
  cleanmyhouse:
    image: cmh/cleanmyhouse:test
    build:
      context: ./CleanMyHouse
      dockerfile: Dockerfile
    ports: 
      - "8000:80"

  user:
    image: cmh/user:test
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile
    ports: 
      - "8002:80"

  building:
    image: cmh/building:test
    build:
      context: .
      dockerfile: Services/Building/Building.API/Dockerfile
    ports: 
      - "8001:80"

  rabbitmq:
    image: rabbitmq:3.9.3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq