version: '3.4'

services:
  cleanmyhouse:
    image: cmh/cleanmyhouse:test
    build:
      context: ./CleanMyHouse
      dockerfile: Dockerfile
    ports: 
      - "8000:80"

  user:
    image: cmh/user:test
    build:
      context: ./User
      dockerfile: Dockerfile
    ports: 
      - "8002:80"

  building:
    image: cmh/building:test
    build:
      context: ./Building
      dockerfile: Dockerfile
    ports: 
      - "8001:80"