"""empty message

Revision ID: b03175ad7343
Revises: 7cfd5e934654
Create Date: 2022-04-14 11:59:18.619984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b03175ad7343"
down_revision = "7cfd5e934654"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
